#!/usr/bin/bash

# Pod is blocked while below is != false
# make below = false to continue/unhold/unblock
POD_ANNOTATION="hold_pod_creation"
HOLD_TIMEOUT="20m"

[[ -n "$CNI_ARGS" ]] && export ${CNI_ARGS//;/ }

LOGFILE=/tmp/hold.log
_log() {
    echo "$@" >> $LOGFILE
}

_log "==================="
_log "$(date)"

# If it is minikube, then adjust some vars
MINIKUBE_KUBECONFIG="/etc/kubernetes/admin.conf"
[[ -e "$MINIKUBE_KUBECONFIG" ]] && {
    _log "Minikube is used"
    export KUBECTL=$(ls -1 /var/lib/minikube/binaries/*/kubectl | head -n1)
    export KUBECONFIG="$MINIKUBE_KUBECONFIG"
}

# Is OCP?
HOLD_D="/etc/cni/net.d/hold.d/"
CNI_KUBECONFIG="$HOLD_D/kubeconfig"
CNI_TOKEN="$HOLD_D/serviceaccount/token"
[[ -e "$CNI_TOKEN" ]] && {
    _log "CNI Hold token is used"
    export KUBECTL="kubectl --token='$(<$CNI_TOKEN)'"
    export KUBECONFIG="$CNI_KUBECONFIG"
}


_log "Handling command '$CNI_COMMAND'"
_log "for pod '$K8S_POD_NAMESPACE/$K8S_POD_NAME'"
_log "$(env | sort)"
_log "$($KUBECTL auth whoami)"

case $CNI_COMMAND in
ADD)
    res=$(cat)
    _log "adding pod '$K8S_POD_NAMESPACE/$K8S_POD_NAME'"
    {
       WCMD=${KUBECTL:-kubectl}
       WCMD+=" wait --for=jsonpath='{.metadata.annotations.$POD_ANNOTATION}'=\"false\""
       WCMD+=" --timeout=$HOLD_TIMEOUT"
       WCMD+=" -n $K8S_POD_NAMESPACE pod $K8S_POD_NAME"
       echo $WCMD
       eval $WCMD
    } >> $LOGFILE 2>&1
    date >> /tmp/hold.tee
    echo -e $res | tee -a /tmp/hold.tee
    echo "" >> /tmp/hold.tee


    _log "Adding done"
    ;;
DEL)
    _log "Delete done"
    ;;
GET)
    ;;
CHECK)
    ;;
VERSION)
    cat <<EOF
{
  "cniVersion": "0.3.1", 
  "supportedVersions": [ "0.3.0", "0.3.1", "0.4.0" ]
}
EOF
    ;;

  *)
    echo "Unknown cni command: '$CNI_COMMAND'"
    exit 1
  ;;
esac
