apiVersion: v1
kind: Pod
metadata:
  name: fedora
  annotations:
    hold_pod_creation: "true"
    "k8s.v1.cni.cncf.io/networks": "hold-prototype-cni"
spec:
  terminationGracePeriodSeconds: 0
  containers:
  - image: quay.io/fedora/fedora:latest
    command:
      - sleep
      - "3600"
    imagePullPolicy: IfNotPresent
    name: fedora
  restartPolicy: Always
