FROM ubi8/ubi
WORKDIR /app

RUN curl -L "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl" -o /usr/local/bin/kubectl && chmod a+x /usr/local/bin/kubectl
RUN dnf install -y jq

ADD image/* /app
ADD cni/* /app
ENTRYPOINT bash /app/entry.sh
